### ISSUE TITLE
missing requirements.txt (/setup.py) detailin requirements

### ISSUE THREAD

**Issue by ghost** [skorokithakis/python-fuse-sample#2]
since the pypi package is not named `fuse` it would be really helpful to document the package this is built to work with in the usual places, requirements.txt or setup.py

**Comment by ensonic** [comment]
From looking at
https://github.com/terencehonles/fusepy/blob/master/examples/loopback.py
this example is using fusepy and not python-fuse

**Comment by skorokithakis** [comment]
It's been a while since I ran this (and since you posted this, sorry for the delay, wasn't receiving notifications). I would accept a PR for this, thank you!

**Comment by ghost** [comment]
https://github.com/skorokithakis/python-fuse-sample/pull/3 :bow:

**Comment by skorokithakis** [comment]
Thanks!
